{
 "title": "Nginx实例",
 "description": "nginx stats , nginx-module-vts  status format prometheus",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nginx_vts_info, instance)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(nginx_vts_server_bytes_total, host)"
    }
   },
   {
    "name": "Upstream",
    "query": {
     "query": "label_values(nginx_vts_upstream_bytes_total, upstream)"
    }
   },
   { "name": "code", "label": "HTTP状态码", "query": "2xx,3xx,4xx,5xx" },
   { "name": "top", "query": "5,10,20,30" }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总请求数",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{status=\"accepted\"}",
     "legendFormat": "已接受"
    },
    {
     "expr": "nginx_vts_main_connections{status=\"handled\"}",
     "legendFormat": "已处理"
    },
    {
     "expr": "nginx_vts_main_connections{status=\"requests\"}",
     "legendFormat": "总请求"
    }
   ]
  },
  {
   "title": "版本信息",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nginx_vts_info{}-0" },
    {
     "expr": "nginx_vts_main_connections{status=\"active\"}-0"
    },
    {
     "expr": "nginx_vts_main_shm_usage_bytes{shared=\"max_size\"}-0"
    },
    {
     "expr": "nginx_vts_main_shm_usage_bytes{shared=\"used_size\"}-0"
    }
   ]
  },
  {
   "title": "运行时间(uptime)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - nginx_vts_start_time_seconds{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "平台延迟统计【ms】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nginx_vts_filter_request_seconds{filter_name=~\"android|windows|ios|unknown\"}",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "接口每秒请求数",
   "type": "timeseries",
   "description": "统计全部http状态码的和按uri分组",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10,sum(irate(nginx_vts_filter_requests_total{code=~\".*\",filter_name=~\"/.*\"}[30s])) by (filter_name))",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "用户数据发送TOP$top",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top,nginx_vts_filter_bytes_total{filter_name=~\"\\\\d+.\\\\d+.\\\\d+.\\\\d+\",direction=\"out\"})",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "用户数据接收TOP$top",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top,nginx_vts_filter_bytes_total{filter_name=~\"\\\\d+.\\\\d+.\\\\d+.\\\\d+\",direction=\"in\"})",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "用户状态码【$code】 TOP$top",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk($top,nginx_vts_filter_requests_total{filter_name=~\"\\\\d+.\\\\d+.\\\\d+.\\\\d+\",code=~\"$code\"})",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "后端状态码【$code】Top$top",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk($top,nginx_vts_upstream_requests_total{backend=~\"\\\\d+.\\\\d+.\\\\d+.\\\\d+:.*\",code=\"$code\"})",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "前端请求时延【ms】",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nginx_vts_filter_request_seconds{filter_name=~\"/.*\"}",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "nginx向后端请求时延Top$top 【ms】",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top,nginx_vts_filter_request_seconds{filter_name=~\"\\\\d+.\\\\d+.\\\\d+.\\\\d+:.*\"})",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "后端响应时延Top$top【ms】",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top,nginx_vts_upstream_response_seconds{backend=~\"\\\\d+.\\\\d+.\\\\d+.\\\\d+:.*\"})",
     "legendFormat": "{{upstream}}--{{backend}}"
    }
   ]
  },
  {
   "title": "状态码一分钟比率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_filter_requests_total{code=\"3xx\"}[1m]))/sum(rate(nginx_vts_filter_requests_total{code=~\".*\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_vts_filter_requests_total{code=\"4xx\"}[1m]))/sum(rate(nginx_vts_filter_requests_total{code=~\".*\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_vts_filter_requests_total{code=\"5xx\"}[1m]))/sum(rate(nginx_vts_filter_requests_total{code=~\".*\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "其他",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx连接数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Server Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_server_cache_total{host=~\"^$Host$\"}[5m])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Server Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_server_requests_total{instance=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Server Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"^$Host$\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "Upstream Requests",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\",code!=\"total\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "后端响应",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_vts_upstream_response_seconds_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "访问来源(Source)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_filter_request_seconds_total{}[5m])) by(filter_name)  ",
       "legendFormat": "{{filter_name}}"
      }
     ]
    }
   ]
  }
 ]
}