{
 "title": "系统进程",
 "description": "Show Linux Process information as captured by \n https://github.com/ncabatoff/process-exporter  designed for PMM",
 "tags": [ "process" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "主机",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs, instance)"
    }
   },
   { "name": "interval", "label": "间隔", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "processes",
    "label": "进程",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\",mode=\"user\"},groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>数据采集自 </font><font color=#e68a00>$host</font> <font color=#5991A7> 刷新间隔</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7></center></b></font></i></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "进程CPU使用情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "进程使用CPU内核总数Top",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_cpu_seconds_total{mode=\"system\",groupname=~\"$processes\",instance=~\"$host\"}[$interval])\nor\n(irate(namedprocess_namegroup_cpu_seconds_total{mode=\"system\",groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "系统CPU核心Top",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by (groupname,instance)\n(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]))\nor\nsum by (groupname,instance)(irate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "进程内存使用情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用量Top",
     "type": "graph",
     "description": "进程使用的内存，算作常驻内存+交换空间使用的空间",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\r\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[$interval])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[$interval]))\r\nor\r\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[5m])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[5m]))\r\n))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "常驻内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[$interval]) \nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[5m])\n))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "虚拟内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$host\"}[$interval])\nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$host\"}[5m])))\n",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Swap内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[$interval])\nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[5m])))\n",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "进程磁盘IO使用情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "写入/Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or irate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "读取/Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or irate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "进程和线程数",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "进程数Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(max_over_time(namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) \nor max_over_time(namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "线程Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(max_over_time(namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "上下文切换",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "自愿上下文切换Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "非自愿上线文切换Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "文件描述符",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "打开文件描述符Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(max_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "文件描述符百分比Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_worst_fd_ratio{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_worst_fd_ratio{groupname=~\"$processes\",instance=~\"$host\"}[5m])\n))*100",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Page Faults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "页面错误Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nrate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "次要页面错误Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nrate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "进程状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "运行中Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Running\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Running\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "等待IO的进程Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[5m])))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "进程内核等待 (WCHAN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内核等待 $processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=~\"$host\", groupname=~\"$processes\"}[$interval])) by (wchan) )",
       "legendFormat": "{{wchan}}"
      }
     ]
    },
    {
     "title": "内核等待详细信息 $processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=~\"$host\", groupname=~\"$processes\"}[$interval])) by (wchan,groupname) )",
       "legendFormat": "{{groupname}} : {{wchan}}"
      }
     ]
    }
   ]
  },
  {
   "title": "进程运行时间",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processes by uptime",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "time()-(namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$host\"}>0)"
      }
     ]
    }
   ]
  }
 ]
}